//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPhones
    {
        public int id { get; set; }
        public Nullable<int> idRequest { get; set; }
        public Nullable<int> idPhone { get; set; }
    
        public virtual Phone Phone { get; set; }
        public virtual Request Request { get; set; }
    }
}
